<?php
$pages = [
  'login' => 'pages/login.php',
  'login-process' => 'pages/login-process.php',
  'logout' => 'pages/logout.php',
  'dashboard' => 'pages/admin/dashboard.php',
  'books' => 'pages/admin/books/book.php',
  'categories' => 'pages/admin/categories/categories.php',
  'categories-add' => 'pages/admin/categories/categories-add.php',
  'categories-add-process' => 'pages/admin/categories/categories-add-process.php',
  'categories-edit' => 'pages/admin/categories/categories-edit.php',
  'categories-edit-process' => 'pages/admin/categories/categories-edit-process.php',
  'categories-delete' => 'pages/admin/categories/categories-delete.php',
  'classrooms' => 'pages/admin/classrooms/classroom.php',
  'classrooms-add' => 'pages/admin/classrooms/classroom-add.php',
  'classrooms-add-process' => 'pages/admin/classrooms/classroom-add-process.php',
  'classrooms-edit' => 'pages/admin/classrooms/classroom-edit.php',
  'classrooms-edit-process' => 'pages/admin/classrooms/classroom-edit-process.php',
  'classrooms-delete' => 'pages/admin/classrooms/classroom-delete.php',
  'academic-years' => 'pages/admin/academic_years/academic-year.php',
  'academic-years-add' => 'pages/admin/academic_years/academic-year-add.php',
  'academic-years-add-process' => 'pages/admin/academic_years/academic-year-add-process.php',
  'academic-years-edit' => 'pages/admin/academic_years/academic-year-edit.php',
  'academic-years-edit-process' => 'pages/admin/academic_years/academic-year-edit-process.php',
  'teachers' => 'pages/admin/teachers/teacher.php',
  'teachers-add' => 'pages/admin/teachers/teacher-add.php',
  'teachers-add-process' => 'pages/admin/teachers/teacher-add-process.php',
  'teachers-edit' => 'pages/admin/teachers/teacher-edit.php',
  'teachers-edit-process' => 'pages/admin/teachers/teacher-edit-process.php',
  'students' => 'pages/admin/students/student.php',
  'students-add' => 'pages/admin/students/student-add.php',
  'students-add-process' => 'pages/admin/students/student-add-process.php',
];
?>